# Servicios de almacenamiento de datos
# Desarrollo
services:
  # PostgreSQL
  credit-card-db:
    container_name: credit-card
    image: postgres:12-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - credit-card-data:/var/lib/postgresql/data
    networks:
      - credit-card-network

  # Adminer para conectarse a la base de datos
  # Quitar en despliegue final
  adminer-credit-card-db:
    container_name: credit-card-db_adminer
    image: adminer
    restart: always
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      - credit-card-db
    networks:
      - credit-card-network

  # App de credit-card
  credit-card-app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: credit-card-app
    env_file: .env
    networks:
      - credit-card-network
    depends_on:
      - credit-card-db
      - adminer-credit-card-db

  apache-jacoco:
    image: ubuntu/apache2:latest
    container_name: apache-jacoco
    restart: always
    ports:
      - 8081:80
    volumes:
      - ./build/jacoco:/var/www/html
    depends_on:
      - credit-card-app
    networks:
      - credit-card-network

networks:
  credit-card-network:
    driver: bridge

volumes:
  credit-card-data: