DROP TABLE IF EXISTS TarjetaCredito;
CREATE TABLE IF NOT EXISTS Tarjeta (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    numero VARCHAR(16) NOT NULL,
    clienteID BIGINT NOT NULL,
    fechaCaducidad DATE NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    isDeleted BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (clienteID) REFERENCES Cliente(id)
);

